### ISSUE TITLE
Use of Docusaurus Constants has changed

### ISSUE THREAD

**Issue by Anthony-Gaudino** [cloud-annotations/docusaurus-plugin-openapi#87]
On Docusaurus Beta 13 they seem to have done changes and now the plugin is broken with error:
```
Error: Cannot find module '@docusaurus/core/lib/constants'
Require stack:
- /home/anthony/safe_docs/safe/docs/node_modules/docusaurus-plugin-openapi/dist/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/commands/build.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/index.js
- /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/bin/docusaurus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/anthony/safe_docs/safe/docs/node_modules/docusaurus-plugin-openapi/dist/index.js:25:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at module.exports (/home/anthony/safe_docs/safe/docs/node_modules/import-fresh/index.js:32:59)
    at normalizePluginConfig (/home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:46:61)
    at /home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:138:40
    at Array.map (<anonymous>)
    at initPlugins (/home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:134:10)
    at loadPlugins (/home/anthony/safe_docs/safe/docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:55:40)
```

The Docusaurus constants have been moded to `@docusaurus/utils`.

Please see: https://github.com/facebook/docusaurus/discussions/6099

**Comment by bourdakos1** [comment]
@Anthony-Gaudino This should be fixed in the next release
